# application.yml 10000
# bootsrap.yml configserver 20000 -> 환경설정 우선순위
server:
  port: 20000

spring:
  application:
    name: user-service
  datasource:
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/msa?serverTimezone=Asia/Seoul
    # driver-class-name: com.mysql.cj.jdbc.Driver
    # url: jdbc:mysql://192.168.0.29:3306/msa?characterEncoding=UTF-8&serverTimezone=UTC
  output:
    ansi:
      enabled: always

  # zipkin:
  #   base-url: http://localhost:9411
  #   enabled: true

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.format_sql: true
    show-sql: true
    open-in-view: false

# sql:
#   init:
#     platform: mysql

logging:
  level:
    com.green.userservice.feignclient: DEBUG
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

# management:
#   tracing:
#     sampling:
#       probability: 1.0
#     propagation:
#       consume: B3
#       produce: B3
#   zipkin:
#     tracing:
#       endpoint: http://localhost:9411/api/v2/spans

# jwt 비밀번호

token:
  expiration_time: 86400000
  access_token_expiration_time: 86400 # 하루
  refresh_token_expiration_time: 2592000 # 한달
  secret: abcdefghijklmnopqrstuvwxyz01234567890

gateway:
  ip: 127.0.0.1
