global:
  scrape_interval: 5s
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

scrape_configs:
  - job_name: "spring-boot-app"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["192.168.0.40:10000","192.168.0.40:10001","192.168.0.40:10002"]  # Spring Boot 애플리케이션이 실행 중인 포트
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
# - "first_rules.yml"
# - "second_rules.yml"

