server:
  port: 20020

spring:
  application:
    name: second-service
mh:
  value: the second value

#eureka:
#  instance:
#    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
#  client:
#    service-url:
#      defaultZone: http://eurekaserver:8761/eureka
#    fetch-registry: true
#    register-with-eureka: true


