server:
  port: 20010

spring:
  application:
    name: first-service
mh:
  value: my first value

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    tags:
      application: monitoring